### PR TITLE
Converting notebooks to runnable scripts

### PR DESCRIPTION
**Pull request by EliavSh**
converted the notebooks of all different RAG techniques to runnable scripts.
all the scripts have been manually tested and are able to recreate the notebooks' results.

### CODE REVIEW

**Comment by NirDiamant** [comment]
Please:
1) make the code more organized.
2) add "main" function to each file, and call it from if __name__ =="__main__"
3) any code has to be documented

**Comment by EliavSh** [comment]
Hi Nir, thank you for the response :)

General note - I tried to keep the scripts as "analogical" as possible to the notebooks - so any developer that understand one of these, will easily get into the other one.

1. Do you have anything specific that is bothering you about the organization?
2. No problem.
3. (following the general note) I tried to keep things clean - do you think that a reference to the notebooks for "deeper information about the technique" will be enough for that purpose?

**Comment by NirDiamant** [comment]
I believe the most effective approach for handling these scripts is to treat them as if they were part of a pip package.
More specifically, the code in the .py files should be well-organized rather than simply a concatenation of all the cells. This means structuring the code with clearly defined functions at the beginning and including a main function that executes the logic based on user parameters. Additionally, it would be beneficial to include the examples currently in the notebooks in a separate function. This function should be tested to demonstrate that the logic works as expected.

**Comment by NirDiamant** [comment]
amazing!!! thanks

**Pull request merged**
