### PR TITLE
Semantic Chunk RAG - Runnable Script

### PR DESCRIPTION
**Pull request by EliavSh**
1. added semantic_chunking.py
2. changed the structure of simple_rag.py
3. added missing imports to helper_functions.py and raptor.ipynb

### CODE REVIEW

**Comment by EliavSh** [comment]
Hi @NirDiamant  :)

I opened this PR with another RAG method as a runnable script. This time, I've shifted the structure towards a more object-oriented style, which I believe could be applied to all the other RAG methods moving forward.

I'd love to hear your thoughts on the approach and the structure. Let me know what you think! :)

**Comment by NirDiamant** [comment]
looks great to me! I liked the OOP version attitude as well.
just please checkout the master and update the README as well

**Comment by EliavSh** [comment]
Done :)

**Comment by NirDiamant** [comment]
amazing :)

**Pull request merged**
