### PR TITLE
Added Notebook for adaptive rag as well updated the neccessary librar…

### PR DESCRIPTION
**Pull request by Aaryaveerkrishna23**
I have added a notebook for adaptive RAG and updated the necessary libraries in the requirements.txt file.

This adaptive Retrieval-Augmented Generation (RAG) system dynamically routes user queries based on their complexity into different pipelines. The adaptive RAG framework enhances response accuracy by selecting the appropriate strategy for handling queries, ensuring efficient processing for both simple and complex requests.

In this RAG tutorial, I used Google's Gemini model as an LLM and implemented a prompt router to route queries based on their usage.

rag_gemini

### CODE REVIEW

**Comment by NirDiamant** [comment]
Hey! There is already a tutorial for adaptive RAG, what is the difference?
:)

**Comment by Aaryaveerkrishna23** [comment]
I hope you are referring to adaptive_retrieval.ipynb. In that notebook, the author uses an LLM to trigger the pipeline based on the complexity of the query. However, in my approach, I use a semantic prompt router to classify the query and trigger various pipelines accordingly.

For example, in an enterprise HR RAG chatbot, one could store past queries related to different activities, such as payroll, in separate utterances. This allows for more efficient retrieval and organization. To ensure "consistent answers," query responses can be cached in advance, reducing the number of LLM calls, which is critical for organizations.

Additionally, the other notebook predominantly uses LangChain. In contrast, I haven't used any wrappers like LangChain, so my solution is easier to integrate with tools like DSpy, which is gaining popularity. This RAG system is designed with enterprise use cases in mind.

**Comment by NirDiamant** [comment]
I went over the tutorial and found it not relevant to RAG; it’s more of a demonstration on using routing in a chatbot.

Please take a look at my other repo, **GenAI_Agents**. There's an example using LangChain here: [Customer Support Agent with LangGraph](https://github.com/NirDiamant/GenAI_Agents/blob/main/all_agents_tutorials/customer_support_agent_langgraph.ipynb).

Let me know if you find it similar.

**Comment by Aaryaveerkrishna23** [comment]
Yes, it is somewhat similar, but the main difference is that I am using semantic similarity instead of prompting. This way, I won’t need to rely on prompts if I decide to change LLMs in the future.

**Pull request closed without merging**
